backend:
  name: git-gateway
  branch: master
  site_domain: localhost:8000

publish_mode: editorial_workflow
media_folder: static/assets/uploads
public_folder: /assets/uploads
display_url: https://eloquent-lalande-8cc180.netlify.com
logo_url: /assets/logo_large.png

collections:
  - name: "products"
    label: "Products"
    folder: "src/pages/products"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Is Active", name: "is_active", widget: "boolean", default: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: Price, name: price, widget: string}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: Cover Image, name: cover_image, widget: image}
      - label: Image Gallery
        name: image_gallery
        widget: list
        fields:
          - {label: Image, name: image, widget: image}
          - {label: "Color Name", name: "color_name", widget: "string"}
          - {label: "Color Hexadecimal", name: "color_hex", widget: "string"}
  - name: "projects"
    label: "Projects"
    folder: "src/pages/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "project-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Is Selected", name: "is_selected", widget: "boolean", default: false}
      - {label: "Project Assistant", name: "project_assistant", widget: "string"}
      - {label: "Photo Credits", name: "photo_credits", widget: "string"}
      - {label: "Producer", name: "producer", widget: "string"}
      - {label: "Year", name: "year", widget: "date", format: "YYYY"}
      - {label: "Publish Date", name: "publish_date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: Image Gallery
        name: image_gallery
        widget: list
        fields:
          - {label: Image, name: image, widget: image}
          - {label: "Is Cover", name: "is_cover", widget: "boolean"}
  - name: "press"
    label: "Press"
    folder: "src/pages/press"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: Template Key, name: templateKey, widget: hidden, default: press-page}
      - {label: Title, name: title, widget: string}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - label: "Cover"
        name: "cover"
        widget: "image"
        media_library:
          config:
            multiple: true
      - {label: Counter Cover, name: counter_cover, widget: image}
      - {label: Content Image Left, name: content_image_left, widget: image}
      - {label: Content Image Right, name: content_image_right, widget: image}
  - name: "texts"
    label: "Texts"
    folder: "src/pages/texts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "text-page"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "explorations"
    label: "Explorations"
    folder: "src/pages/explorations"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "exploration-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: Image, name: image, widget: image}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Body", name: "body", widget: "markdown"}
