backend:
  name: git-gateway
  branch: master
  site_domain: localhost:8000

publish_mode: editorial_workflow
media_folder: static/assets/uploads
public_folder: /assets/uploads
display_url: https://eloquent-lalande-8cc180.netlify.com
logo_url: /assets/logo_large.png

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/pages/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "projects"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Is Selected", name: "is_selected", widget: "boolean"}
      - {label: "Project Assistant", name: "project_assistant", widget: "string"}
      - {label: "Photo Credits", name: "photo_credits", widget: "string"}
      - {label: "Producer", name: "producer", widget: "string"}
      - {label: "Year", name: "year", widget: "date", format: "YYYY"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: Image Gallery
        name: image_gallery
        widget: list
        fields:
          - {label: Image, name: image, widget: image}
          - {label: "Is Cover", name: "is_cover", widget: "boolean"}
  - name: "texts"
    label: "Texts"
    folder: "src/pages/texts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "projects"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "explorations"
    label: "Explorations"
    folder: "src/pages/explorations"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "explorations"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: Image Gallery
        name: image_gallery
        widget: list
        fields:
          - {label: Image, name: image, widget: image}
          - {label: "Is Cover", name: "is_cover", widget: "boolean"}