backend:
  name: git-gateway
  branch: master
  site_domain: localhost:8000

publish_mode: editorial_workflow
media_folder: static/assets/uploads
public_folder: /assets/uploads
display_url: https://eloquent-lalande-8cc180.netlify.com
logo_url: https://eloquent-lalande-8cc180.netlify.com/static/logo_large-7a558ae26e74241eef861563ebad3b2c.png

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
